-- A2 Outdoor Services secure owner setup
-- Run this in Supabase SQL Editor after creating your project.
-- Create your owner account in Authentication > Users first.

create table if not exists public.owner_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.owner_access enable row level security;

create policy "Owners can read their own access row"
on public.owner_access
for select
to authenticated
using (auth.uid() = user_id);

-- After creating the owner user, replace YOUR_OWNER_USER_UUID below with that user's UUID
-- and run the insert.
-- insert into public.owner_access (user_id) values ('YOUR_OWNER_USER_UUID');

-- Example protected bookings table. Add only the columns you actually need.
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  service text not null,
  booking_date timestamptz not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.bookings enable row level security;

create policy "Only approved owner can read bookings"
on public.bookings
for select
to authenticated
using (exists (select 1 from public.owner_access oa where oa.user_id = auth.uid()));

create policy "Only approved owner can change bookings"
on public.bookings
for all
to authenticated
using (exists (select 1 from public.owner_access oa where oa.user_id = auth.uid()))
with check (exists (select 1 from public.owner_access oa where oa.user_id = auth.uid()));
